# Generated by Django 5.2.6 on 2025-09-26 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid_wi', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование работы')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='Ед. изм.')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('document_url', models.URLField(blank=True, verbose_name='Ссылка на документ')),
            ],
            options={
                'verbose_name': 'Позиция перечня работ',
                'verbose_name_plural': 'Позиции перечня работ',
                'ordering': ['start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid_obj', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('can_proceed', models.BooleanField(default=True, verbose_name='Можно продолжать стройку')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_objects', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_objects', to=settings.AUTH_USER_MODEL, verbose_name='Прораб')),
                ('iko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iko_objects', to=settings.AUTH_USER_MODEL, verbose_name='ИКО')),
                ('ssk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssk_objects', to=settings.AUTH_USER_MODEL, verbose_name='ССК')),
            ],
            options={
                'verbose_name': 'Объект строительства',
                'verbose_name_plural': 'Объекты строительства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid_schedule', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('planned_start', models.DateField(verbose_name='План. начало')),
                ('planned_end', models.DateField(verbose_name='План. окончание')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('done', 'Выполнено')], default='planned', max_length=16, verbose_name='Статус')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='api.constructionobject', verbose_name='Объект')),
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_item', to='api.workitem', verbose_name='Позиция перечня')),
            ],
            options={
                'verbose_name': 'Элемент расписания',
                'verbose_name_plural': 'Расписание объекта',
                'ordering': ['planned_start', 'planned_end'],
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid_wp', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Для удобства поиска/версий', max_length=255, verbose_name='Название перечня')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал (ССК/админ)')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_plans', to='api.constructionobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Перечень работ',
                'verbose_name_plural': 'Перечни работ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.workplan', verbose_name='Перечень'),
        ),
    ]
