# Generated by Django 5.2.6 on 2025-09-30 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_memo_constructionobject_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='ssk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssk_objects', to=settings.AUTH_USER_MODEL, verbose_name='ССК'),
        ),
    ]
