# Generated by Django 5.2.6 on 2025-09-30 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_constructionobject_ssk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid_area', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID области')),
                ('name', models.CharField(max_length=255, verbose_name='Название области')),
                ('geometry', models.JSONField(help_text='Polygon или MultiPolygon в формате GeoJSON', verbose_name='GeoJSON geometry')),
            ],
            options={
                'verbose_name': 'Область/полигон',
                'verbose_name_plural': 'Области/полигоны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
