# Generated by Django 5.2.6 on 2025-09-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_area_delete_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.constructionobject', verbose_name='Объект строительства'),
        ),
    ]
