# Generated by Django 5.2.6 on 2025-10-01 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_area_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с файлами на FTP сервере', verbose_name='URL папки на FTP'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid_material', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID материала')),
                ('material_name', models.CharField(max_length=255, verbose_name='Наименование материала')),
                ('material_quantity', models.CharField(blank=True, max_length=100, verbose_name='Количество материала')),
                ('material_size', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('material_volume', models.CharField(blank=True, max_length=100, verbose_name='Объем')),
                ('material_netto', models.CharField(blank=True, max_length=100, verbose_name='Нетто')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.delivery', verbose_name='Поставка')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.invoice', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-created_at'],
            },
        ),
    ]
