# Generated by Django 5.2.6 on 2025-10-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoice_folder_url_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10, verbose_name='Уровень')),
                ('category', models.CharField(choices=[('auth', 'Авторизация'), ('object', 'Объекты'), ('delivery', 'Поставки'), ('prescription', 'Нарушения'), ('work_plan', 'Графики работ'), ('activation', 'Активация'), ('user', 'Пользователи'), ('area', 'Полигоны'), ('system', 'Система'), ('api', 'API')], default='system', max_length=20, verbose_name='Категория')),
                ('message', models.TextField(verbose_name='Подробное сообщение')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='api_log_level_c666d8_idx'), models.Index(fields=['category'], name='api_log_categor_802ae9_idx'), models.Index(fields=['created_at'], name='api_log_created_b853ac_idx')],
            },
        ),
    ]
