# Generated by Django 5.2.6 on 2025-10-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('activation_pending', 'Ожидает активации'), ('active', 'Активен'), ('suspended', 'Приостановлен'), ('completed_by_ssk', 'Завершён ССК'), ('completed', 'Завершён')], default='draft', max_length=32, verbose_name='Статус'),
        ),
    ]
