# Generated by Django 5.2.6 on 2025-10-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_constructionobject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='documents_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с документами объекта в файловом хранилище', verbose_name='URL папки с документами объекта'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='invoice_photos_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с фото накладных в файловом хранилище', verbose_name='URL папки с фото накладных'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='violation_photos_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с фото нарушения в файловом хранилище', verbose_name='URL папки с фото нарушения'),
        ),
        migrations.AddField(
            model_name='prescriptionfix',
            name='fix_photos_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с фото исправления нарушения в файловом хранилище', verbose_name='URL папки с фото исправления'),
        ),
    ]
