# Generated by Django 5.2.6 on 2025-10-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_constructionobject_documents_folder_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('auth', 'Авторизация'), ('object', 'Объекты'), ('delivery', 'Поставки'), ('prescription', 'Нарушения'), ('work_plan', 'Графики работ'), ('activation', 'Активация'), ('user', 'Пользователи'), ('area', 'Полигоны'), ('system', 'Система'), ('api', 'API'), ('file_storage', 'Файловое хранилище')], default='system', max_length=20, verbose_name='Категория'),
        ),
    ]
