# Generated by Django 5.2.6 on 2025-10-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_log_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='documents_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с документами объекта в файловом хранилище', max_length=10000, verbose_name='URL папки с документами объекта'),
        ),
        migrations.AlterField(
            model_name='dailychecklist',
            name='photos_folder_url',
            field=models.URLField(blank=True, max_length=10000, verbose_name='URL папки с фото'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='invoice_photos_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с фото накладных в файловом хранилище', max_length=10000, verbose_name='URL папки с фото накладных'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с файлами на FTP сервере', max_length=10000, verbose_name='URL папки на FTP'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='violation_photos_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с фото нарушения в файловом хранилище', max_length=10000, verbose_name='URL папки с фото нарушения'),
        ),
        migrations.AlterField(
            model_name='prescriptionfix',
            name='fix_photos_folder_url',
            field=models.URLField(blank=True, help_text='Ссылка на папку с фото исправления нарушения в файловом хранилище', max_length=10000, verbose_name='URL папки с фото исправления'),
        ),
    ]
