# Generated by Django 5.2.6 on 2025-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_constructionobject_documents_folder_url_and_more'),
    ]

    operations = [
        # Шаг 1: Добавляем новое поле JSONField
        migrations.AddField(
            model_name='prescription',
            name='violation_photos_folder_url_new',
            field=models.JSONField(blank=True, default=list, help_text='Массив ссылок на фото нарушения в файловом хранилище', verbose_name='URL папки с фото нарушения (новое)'),
        ),
        
        # Шаг 2: Копируем данные из старого поля в новое с помощью SQL
        migrations.RunSQL(
            """
            UPDATE api_prescription 
            SET violation_photos_folder_url_new = 
                CASE 
                    WHEN violation_photos_folder_url IS NULL OR violation_photos_folder_url = '' 
                    THEN '[]'::json
                    ELSE ('["' || violation_photos_folder_url || '"]')::json
                END;
            """,
            reverse_sql="""
            UPDATE api_prescription 
            SET violation_photos_folder_url_new = '[]'::json;
            """
        ),
        
        # Шаг 3: Удаляем старое поле
        migrations.RemoveField(
            model_name='prescription',
            name='violation_photos_folder_url',
        ),
        
        # Шаг 4: Переименовываем новое поле
        migrations.RenameField(
            model_name='prescription',
            old_name='violation_photos_folder_url_new',
            new_name='violation_photos_folder_url',
        ),
    ]
