# Generated by Django 5.2.6 on 2025-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_prescription_violation_photos_folder_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='documents_folder_url',
            field=models.JSONField(blank=True, default=list, help_text='Массив ссылок на документы объекта в файловом хранилище', verbose_name='URL папки с документами объекта'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='invoice_photos_folder_url',
            field=models.JSONField(blank=True, default=list, help_text='Массив ссылок на фото накладных в файловом хранилище', verbose_name='URL папки с фото накладных'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='violation_photos_folder_url',
            field=models.JSONField(blank=True, default=list, help_text='Массив ссылок на фото нарушения в файловом хранилище', verbose_name='URL папки с фото нарушения'),
        ),
        migrations.AlterField(
            model_name='prescriptionfix',
            name='fix_photos_folder_url',
            field=models.JSONField(blank=True, default=list, help_text='Массив ссылок на фото исправления нарушения в файловом хранилище', verbose_name='URL папки с фото исправления'),
        ),
    ]
