# Generated by Django 5.2.6 on 2025-10-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_constructionobject_documents_folder_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychecklist',
            name='pdf_url',
        ),
    ]
