# Generated by Django 5.2.6 on 2025-10-17 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_dailychecklist_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название подобласти/подполигона')),
                ('geometry', models.JSONField(help_text='Polygon или MultiPolygon в формате GeoJSON', verbose_name='GeoJSON geometry')),
                ('color', models.CharField(default='#FF0000', help_text='HEX цвет, например #RRGGBB', max_length=7, verbose_name='Цвет')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='api.area', verbose_name='Родительская область')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_areas', to='api.workitem', verbose_name='Позиция перечня работ')),
            ],
            options={
                'verbose_name': 'Подобласть/подполигон',
                'verbose_name_plural': 'Подобласти/подполигоны',
                'ordering': ['-created_at'],
            },
        ),
    ]
