# Generated by Django 5.2.6 on 2025-10-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_subarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.workitem', verbose_name='Позиция перечня работ'),
        ),
    ]
