# Generated by Django 5.2.6 on 2025-10-17 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delivery_work_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid_change_request', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID запроса на изменение')),
                ('changes_data', models.JSONField(default=dict, help_text='JSON с изменениями позиций', verbose_name='Данные изменений')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Принято'), ('rejected', 'Отклонено'), ('edited', 'Отредактировано')], default='pending', max_length=16, verbose_name='Статус')),
                ('old_items_data', models.JSONField(default=list, help_text='JSON с исходными данными позиций', verbose_name='Старые данные позиций')),
                ('new_items_data', models.JSONField(default=list, help_text='JSON с предлагаемыми данными позиций', verbose_name='Новые данные позиций')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял решение')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_item_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто запросил')),
                ('work_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_change_requests', to='api.workplan', verbose_name='Перечень работ')),
            ],
            options={
                'verbose_name': 'Запрос на изменение позиций перечня',
                'verbose_name_plural': 'Запросы на изменение позиций перечня',
                'ordering': ['-created_at'],
            },
        ),
    ]
