# Generated by Django 5.2.6 on 2025-10-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_workitemchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('completed_foreman', 'Завершено прорабом'), ('completed_ssk', 'Завершено ССК')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
